table Date
	lineageTag: d180b419-0734-4716-82bc-7e79cac2768c

	column DateKey
		dataType: int64
		formatString: 0
		lineageTag: 342607e2-d509-493f-98ef-d3b976f3895d
		summarizeBy: none
		sourceColumn: DateKey

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: e16df201-df0f-4e24-baa7-0f564192414a
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Fiscal Year'
		dataType: string
		lineageTag: f04818aa-4d11-46fa-bd77-f51b9a80309f
		summarizeBy: none
		sourceColumn: Fiscal Year

		annotation SummarizationSetBy = Automatic

	column 'Fiscal Quarter'
		dataType: string
		lineageTag: 151d4216-7456-4eb7-bb26-6031d15a198e
		summarizeBy: none
		sourceColumn: Fiscal Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: dateTime
		formatString: Long Date
		lineageTag: 3c61c730-6c64-4d8f-9f93-edbeae7afccb
		summarizeBy: none
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Full Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 34391bbf-f9c7-41d1-938b-6ca7372f5035
		summarizeBy: none
		sourceColumn: Full Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column MonthKey
		dataType: int64
		formatString: 0
		lineageTag: 360cbd21-1452-4c90-978f-77b115b89074
		summarizeBy: none
		sourceColumn: MonthKey

		annotation SummarizationSetBy = Automatic

	column 'Start of Week'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 856adf8f-85e7-4e31-92eb-e040f4c4122d
		summarizeBy: none
		sourceColumn: Start of Week

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition Date = m
		mode: import
		source =
				let
				    Source = excel_source,
				    Date_Table = Source{[Item="Date",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(Date_Table,{{"DateKey", Int64.Type}, {"Date", type date}, {"Fiscal Year", type text}, {"Fiscal Quarter", type text}, {"Month", type date}, {"Full Date", type date}, {"MonthKey", Int64.Type}}),
				    #"Inserted Start of Week" = Table.AddColumn(#"Changed Type", "Start of Week", each Date.StartOfWeek([Date]), type date)
				in
				    #"Inserted Start of Week"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

