table Reseller
	lineageTag: 59552df8-eb05-46a6-881a-746daf2c3c9f

	column ResellerKey
		dataType: int64
		formatString: 0
		lineageTag: 8eda723f-90c7-45b2-ab53-221391a914de
		summarizeBy: none
		sourceColumn: ResellerKey

		annotation SummarizationSetBy = Automatic

	column 'Reseller ID'
		dataType: string
		lineageTag: cdbf9d5f-543a-47f4-b13b-bc8a7d2d4dcd
		summarizeBy: none
		sourceColumn: Reseller ID

		annotation SummarizationSetBy = Automatic

	column 'Business Type'
		dataType: string
		lineageTag: 44138405-8498-41ef-a028-18f2879a032f
		summarizeBy: none
		sourceColumn: Business Type

		annotation SummarizationSetBy = Automatic

	column Reseller
		dataType: string
		lineageTag: efa8a6b0-7bf1-4b4c-9d64-c4112f8f8645
		summarizeBy: none
		sourceColumn: Reseller

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: 2b987215-e47d-4bee-ae25-c48a498eda34
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column State-Province
		dataType: string
		lineageTag: 6d0c447f-4265-4a2a-b5bd-5f60e5b64628
		summarizeBy: none
		sourceColumn: State-Province

		annotation SummarizationSetBy = Automatic

	column Country-Region
		dataType: string
		lineageTag: 1829641f-a7c0-4dec-8a62-2f47d809f575
		summarizeBy: none
		sourceColumn: Country-Region

		annotation SummarizationSetBy = Automatic

	column 'Postal Code'
		dataType: string
		lineageTag: 4b5c2081-de2c-4bc5-87c7-f8f9a7ba40d1
		summarizeBy: none
		sourceColumn: Postal Code

		annotation SummarizationSetBy = Automatic

	partition Reseller = m
		mode: import
		source =
				let
				    Source = excel_source,
				    Reseller_Table = Source{[Item="Reseller",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(Reseller_Table,{{"ResellerKey", Int64.Type}, {"Reseller ID", type text}, {"Business Type", type text}, {"Reseller", type text}, {"City", type text}, {"State-Province", type text}, {"Country-Region", type text}, {"Postal Code", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

